### ISSUE TITLE
Make logging optional

### ISSUE THREAD

**Issue by alecmev** [davidjbradshaw/eslint-config-auto#59]
Same as `adjunct`: https://github.com/davidjbradshaw/eslint-config-adjunct/pull/48 Breaks `LSP-eslint` otherwise: https://github.com/sublimelsp/LSP/issues/2013 There's a fix coming, but it might take ages to ship.

**Comment by davidjbradshaw** [comment]
This looks like LSP got fixed.

**Comment by alecmev** [comment]
I'm afraid not. The PR is still blocked, currently using Yarn-level patching (just changing all `.log` to `.error`, in `adjunct` too).
